database: mysql
spring:
    datasource:
        initialization-mode: always
        password: rentcar
        url: jdbc:mysql://192.168.99.100/rentcar?useSSL=false&allowPublicKeyRetrieval=true
        username: root
    jpa:
      hibernate:
        use-new-id-generator-mappings: false
